### ISSUE TITLE
Pick a default set of media types for @EnableHypermediaSupport

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-hateoas#1015]
Instead of manually requiring setting the `types` field when using this annotation, let's select a default set of media types, whether that's simply `HAL` to match what is done historically, or whether it's to enable all support media types.

Or perhaps we can it be a little more sophisticated and have an `HypermediaType` type that says to activate all discovered media types dynamically.

**Comment by odrotbohm** [comment]
I remember having a discussion with @wilkinsona about this. The challenge here is to make things reasonably but at the same time to be careful that we don't necessarily change user's APIs just because we decide to add support for a new media type as that might be surprising.

We also have to make up our minds on how explicitly activating media type support contributed via an extension plays into this.

**Comment by gregturn** [comment]
Is go for at least these options (if it’s not too complicated):

* LEGACY - activates HAL and nothing else
* SUPPORTED - activates all of the supported but not 3rd party
* SCANNED - activates all 3rd party types
* SUPPORTED_AND_SCANNED - everything

The names are up for grabs but these seem like the most logical groupings to me. If we also need something for HAL + HAL_FORMS I also wouldn’t object.

**Comment by gregturn** [comment]
Spring Boot simply has `@EnableHypermediaSupport(HAL)`, which defaults to HAL. Check out #1060, and its ability to allow users to simply use `@EnableHypermediaSupport`, and have ALL registered hypermedia supports enabled.

**Comment by gregturn** [comment]
Closing this out in favor of letting #1060 support a "null" or "empty" configuration, where it will NOT enable any of our pre-built hypermedia types, and instead simply fall back to whatever custom ones the user has designed.
