### ISSUE TITLE
Feature request: make it easier to linkTo controller methods returning void

### ISSUE THREAD

**Issue by Dretch** [spring-projects/spring-hateoas#1173]
Right now you can't use the `WebMvcLinkBuilder.linkTo(methodOn(SomeController.class).someMethod()).withRel(..)` helpers if `someMethod` returns `void`. The generic type of `linkTo` is just not compatible with `void` methods.

There is a reasonable workaround: just change the method to return `ResponseEntity<void>` instead of `void`, but I wonder if this could be made easier (and not require changing the controller code).

I can imagine an overloaded version of `linkTo` with a type signature like:
```java
public static WebMvcLinkBuilder linkTo(Runnable invocationValueSupplier) { ... }
```

You could then call this with something like: `linkTo(() -> methodOn(SomeController.class).someMethod()).withRel(..)`

I am not sure if the internal link building machinery would support this... but if it could then I think it would be neat.

**Comment by gregturn** [comment]
Did a little digging into this issue. 

When you use `linkTo(methodOn(SomeContoller.class).someMethod())`, you're kind of stuck. And that's by basic Java.

If `someMethod()` looked like this:

```java
@PostMapping("/process")
void someMethod() {
	// Does some processing
}
```
...then the return type of that method is `void`. The way the `methodOn()` operator works is by wrapping the thing in a proxy and invoking it. But the return type is the same as your method's return type. `void` in this case.

And feeding a `void` into `linkTo()` just isn't possible. In fact, `void` is not a valid input type for ANY method.

So `linkTo(methodOn())` just isn't available. Because `WebMvcLinkBuilder` is built up on bits of reflection, you are able to do this:

```java
@Test // #1173
void shouldBuildLinkToMethodWithVoidReturnType() {

	Method processMethod = ReflectionUtils.findMethod(SomeController.class, "someMethod");

	Link link = linkTo(processMethod, Collections.emptyList()).withSelfRel();

	assertThat(link.getHref()).endsWith("/something/process");
}
```
This essentially lets you avoid invoking the method and depending upon its return type, and instead just pipes it into `WebMvcLinkBuilder` directly. Of course, to make the compiler aware you're invoking `linkTo(Method)` and NOT `linkTo(Object)`, you have to call the overloaded method with an empty list of arguments.

But this actually works and passes green.

I just fear this solution is worse than the problem. Or worse than altering your controller to return `ResponseEntity<Void>`.

P.S. I labeled this issue as Spring MVC-only, because returning `void` is a big no-no in reactive programming, aka Spring WebFlux.
