### ISSUE TITLE
Feature request: Option to remove _embedded from CollectionModel

### ISSUE THREAD

**Issue by alesaudate** [spring-projects/spring-hateoas#1214]
Today, when returning a CollectionModel from any resource, it seems impossible to render it without `_embedded`. It's possible to disable the deserializer though, but it makes the field to be rendered as `content` instead of `_embedded`. 

The purpose of this feature request would be, then, to wrap the elements in the `content` field at all, and at the same time rendering the links field as usual.

**Comment by gregturn** [comment]
Please clarify the use case in which you need `_embedded` to be removed when dealing with a `CollectionModel`.

**Comment by alesaudate** [comment]
Hi @gregturn , how are you doing ?

I thought about cases outside the HAL model. Rendering it just based in business needs , like communication with clients that are not aware about this model (or don't care). It is kinda odd for this point of view that you request a resource and it turns out that the resource needed is inside some other thing.

**Comment by odrotbohm** [comment]
I am not sure I get what you mean with "outside the HAL model". `_embedded` is part of HAL and you only see it if you're using HAL in the first place. Although it's an optional element, we currently always include it as it's good practice to rather use return empty maps from methods to return `Map` rather than null. I'm assuming type based Jackson binding would translate that into a resulting object as well.

That said, we could a flag to `HaLConfiguration` and evaluate that in `HalResourcesSerializer.serialize(…)`. and skip the rendering. Now that I checked, our `CollectionModelMixin` already declares a `@JsonInclude(NON_EMPTY)`. I.e. if there are no embedds, the clause isn't even rendered in the first place?

Would you mind providing an example that produces a representation and you outlining what's not properly working for you?

**Comment by alesaudate** [comment]
Hi @odrotbohm , how are you doing ?

Your response made me think if I'm doing something wrong, because I always get the `_embedded` element when returning `CollectionModel`, no matter what I try. The most I could get out of it was to return `content` instead of `_embedded`, but in the end it is basically the same. If I'm doing something wrong, please provide me some material where I can see how I can  retrieve the result.


What I need is the same that's described in Stack Overflow: https://stackoverflow.com/questions/28808220/how-to-remove-the-embedded-property-in-spring-hateoas 

Observe how the `technologies` element is unwrapped. 

I took a look on `CollectionModelMixin` and yes, it helps, but that is not quite the problem. It's certainly related, but by no means solves it.

**Comment by gregturn** [comment]
The `_embedded` attribute is a requirement for collection when you render HAL.

If you're trying to get away from HAL, the simplest thing could be rendering directly, using Jackson, our types (`CollectionModel`, `EntityModel`, etc.).

That's easy if you just register your own mediatype. Here's an example:

```java
@Bean
HypermediaMappingInformation antiqueMedia() {
	return new HypermediaMappingInformation() {
		@Override
		public List<MediaType> getMediaTypes() {
			return Arrays.asList(MediaType.parseMediaType("application/antique+json"));
		}
	};
}
```

This will register another mediatype, and basically clone the Jackson `ObjectMapper`, but without registering any special serializers. If you wish to register your own handlers for those types, look into the rest of the `HypermediaMappingInformation` SPI.

**Comment by alesaudate** [comment]
Thanks for the reply. But I just would like to return plain old JSON
(application/json) without any of HAL's structures (specifically
_embedded).  Is it possible?

Em seg, 9 de mar de 2020 16:28, Greg Turnquist <notifications@github.com>
escreveu:

**Comment by odrotbohm** [comment]
What's shown in the StackOverflow post can be achieved, but needs a wrapper object with the `technologies` field present. I could explain everything and the world how to achieve this but I think we'd be better off if you provided actual code for us to then discuss what needs to change. Otherwise we present an idea and you're response (again) is: "Yeah, but my scenario is slightly different." Please show us what you have.

Also, please be reminded that StackOverflow is a better place to ask for how to achieve things. Ultimately, the ticket here is obsolete as `_embedded` is only rendered if it's needed according to the HAL specification and if you use the `RepresentationModel` objects. I am inclined to close the ticket as "works as designed" and would like to redirect you to SO for general question / answer handling.

**Comment by alesaudate** [comment]
I see your point. But it turns out I'm getting the same response as described in the Stack Overflow post with only one difference: I haven't configured anything to enable HAL. Zero. It indeed returns a "application/json" response but with the `_embedded` field in it. By your answers, I'm perceiving this as a bug, then. And should not be a feature request, but a need for bugfix.

**Comment by odrotbohm** [comment]
Yes. It doesn't make sense to use Spring HATEOAS then as you're not using any hypermedia elements. Simply return a `List` or `Map` then.

**Comment by odrotbohm** [comment]
I've commented on the [StackOverflow question](https://stackoverflow.com/a/60609135/18122).
