### ISSUE TITLE
Custom types not supported in HAL FORMS properties description

### ISSUE THREAD

**Issue by Ickbinet** [spring-projects/spring-hateoas#1697]
At the moment HalFormsPropertyFactory.createProperties will convert all types not known by HtmlInputType to null.
This prevents the use of possibly new html input types and of custom types.

**Comment by odrotbohm** [comment]
The HAL FORMS spec [defines a set of supported types](https://rwcbook.github.io/hal-forms/#_code_type_code), which are all included in the `HtmlInputType` constants. Can you elaborate on the problem you see?

**Comment by Ickbinet** [comment]
I am not sure if "possible settings" the spec means MUST or SHOULD. 
HtmlInputType already supports more than these (e.g. file).

Possible solutions would be:

- reject all values not supported by HtmlInputType
- Change the return type of PropertyMetadata.getInputType() from String to HtmlInputType
- allow any string - which I would prefer.

**Comment by odrotbohm** [comment]
The spec doesn't define anything but the listed types supported, so we don't support any other types. I suggest asking for clarification on the spec bug tracker. I prefer to add support for stuff outside the spec after clarification. We can always loosen the constraints. Allowing something to be expressed and moving back later breaks APIs.

`PropertyMetadata.getInputType()`can't be of type `HtmlInputType` because the former is media type agnostic. That `HtmlInputType` is used for HAL FORMS is an implementation detail as accidentally HAL FORMS aligns a lot with the HTML spec. Other media types don't.

**Comment by Ickbinet** [comment]
OK, now that it's quite clear the the type list in the spec is not exhaustive (https://github.com/mamund/hal-forms/issues/88), I reopen the issue.

**Comment by odrotbohm** [comment]
That's fixed and backported to 1.3.x.
