### ISSUE TITLE
Handling versioned-resources with entity links

### ISSUE THREAD

**Issue by vivin** [spring-projects/spring-hateoas#285]
I'm building an API that uses content-negotiation for versioning. This means that I need a DTO per version of the resource. To use entity links, you need to annotate on the controller the resource it is exposing using `@ExposesResourceFor`. However, you can only specify one class and you cannot have multiple `@ExposesResourceFor` annotations. How would I do this with entity links?

I can get by creating the links by pointing to controller methods, but I was curious if this is something you guys would be looking into. 

If there is a better solution to handle versioned resources than having multiple DTO's I'm open to that too!

**Comment by schvanhugten** [comment]
Just helping you think here. You could create your own annotation and add the logic in org.springframework.hateoas.core.ControllerEntityLinks and org.springframework.hateoas.mvc.ControllerRelProvider.

I don't think it would work though because these links map to an empty path. Why would you respond with multiple entities on a single path?

**Comment by vivin** [comment]
My idea was to be able to vend multiple versions (until the old ones get deprecated anyway). I guess my general question is to see how I can use Spring HATEOAS with content-negotiation-based versioning. Thanks for the help! I do need to think about this some more!

**Comment by gregturn** [comment]
For a more detailed discussion, check out #3116.

For those that soldier on and do it anyway, we don't see making API versioning a built-in feature of the framework, i.e. Spring HATEAOS won't _help_ you do it with some provided API.

All that being said, if you really need this, nothing is stopping you from adding another controller with the root of it all having your "/v2" prefix at the top of the controller class. Because Spring HATEOAS is all about "roll your own", you can create all the controllers you need, name them `Version1EmployeeController`, `Version2EmployeeController`, etc. How you use and re-use the underlying DTOs is, again, up to you.

Your controllers (or ModelAssemblers) can be version-specific and do what you want. As long as you keep the differently versioned controllers apart, you should be fine.
