### ISSUE TITLE
Link XmlAttributes aren't namespaced to ATOM

### ISSUE THREAD

**Issue by sdavids13** [spring-projects/spring-hateoas#326]
Currently the atom:link attributes aren't being namespaced, thus this is invalid XML since the atom schema requires a href attribute within the same namespace.

**Comment by olivergierke** [comment]
Any chance you add a test case or some sample code that shows what's not working exactly?

**Comment by benjamin-heasly** [comment]
I encountered this or similar.  For what it's worth, here is an example of what I see:
```
<wstxns2:link>
    <wstxns2:link rel="..." href="..." />
    <wstxns2:link rel="..." href="..." />
</wstxns2:link>
```

I am Marshalling to XML using Jackson and Woodcox, which explains the [wstxns2](https://github.com/FasterXML/woodstox/blob/c412c7175d040a4b93a0069965cf985f50064050/src/main/java/com/ctc/wstx/api/WriterConfig.java#L29).

Jackson has [limited support for Jaxb annotations](http://wiki.fasterxml.com/JacksonJAXBAnnotations).  Looks like Jackson misses the "namespace" field of @XmlType.  See [Jackson source](https://github.com/FasterXML/jackson-module-jaxb-annotations/blob/bdb14d4ac184a40be81df3250e638d52384af688/src/main/java/com/fasterxml/jackson/module/jaxb/JaxbAnnotationIntrospector.java#L622).

This should explain the missing link namespace, since the namespace is specified in XmlType.  See [Spring HATEOAS source](https://github.com/spring-projects/spring-hateoas/blob/master/src/main/java/org/springframework/hateoas/Link.java#L41).

So, this is probably a Jackson issue.

But could Spring HATEOAS also add extra namespace specifications in order to work with more Marshallers?

**Comment by gregturn** [comment]
Superceded by https://github.com/spring-projects/spring-hateoas/pull/695.
