### ISSUE TITLE
Traverson's double encodes URIs

### ISSUE THREAD

**Issue by vicmosin** [spring-projects/spring-hateoas#337]
Somehow Traverson double encodes the empty spaces inside GET parameters...

```
parameters.put("name", "TEST SERVICE");
PagedResources<Resource<Business>> response = traverson
		.follow("search", "findByName")
		.withTemplateParameters(parameters)
		.toObject(new ParameterizedTypeReference<PagedResources<Resource<Business>>>() {});
```

and the request URL looks like: http://localhost:8080/search/findByName?name=TEST%2520SERVICE

As you can see the empty space was encoding twice.. 

spring-starter-data-rest v.1.2.2

**Comment by tommyb82** [comment]
I believe the issue lies between the Traverson class and RestTemplate, with each performing encoding resulting in double-encoded GET parameters.  In the following method:

`Traverson.toObject(String jsonPath)`

The call to the overloaded `RestOperations` exchange method (on an instance of `RestTemplate`) is made using a `String` URI, as returned by `Traverson.TraversalBuilder.traverseToFinalUrl()`.  This returned string is encoded at this point, but by calling the `exchange` method implementation that takes a string, rather than a `URI` instance, the RestTemplate will encode it a second time.

The solution would therefore appear to be to make the call to `RestOperations.exchange` with a URI instance rather than it's String representation.

**Comment by claym** [comment]
Any progress on this? It's kind of a big problem :)

**Comment by gregturn** [comment]
@tommyb82

If you have a PR that would be great. Including a test case would be even better. Be sure to mention this issue number to link them together. It will definitely speed up the pace of getting your fix into the baseline.

**Comment by tommyb82** [comment]
@gregturn @claym 

Hi both - yes we implemented a local patch for this, and the intention is still to offer this back to the community; I will try and get the PR etc sorted this week (sorry - it got pushed down the priority list!).

**Comment by claym** [comment]
No problem. Eager to see the fix though :)

**Comment by tommyb82** [comment]
Hi @gregturn , I've got a test case working in `TraversonTests` for this now, it runs and passes in my IDE but maven seems to ignore all the tests in that class - and others (`JacksonSerializationTests` for example) - something I'm doing wrong obviously.. could you advise? Thanks.

**Comment by gregturn** [comment]
Can you push to a branch so I can poke at it?

**Comment by tommyb82** [comment]
Hi @gregturn just realised its because of the Tests extension I guess which by default won't be picked up by maven..  I've broken another test anyway in the process of fixing the double encoding issue, so need to look at that but curious about the use of the Test**s** suffix in some classes but not others. 

Just pushed what I have so far to https://github.com/tommyb82/spring-hateoas/tree/bugfix/issue337 anyway

**Comment by gregturn** [comment]
A) I checkout out your branch and on first blush, looks like your patch + test case works. B) I can't for the life of me see why maven doesn't run tests inside .alps or .client. I posted this to @olivergierke, given it is also happening on [travis](https://travis-ci.org/spring-projects/spring-hateoas/jobs/78176372).

**Comment by olivergierke** [comment]
The reason for that is indeed that Maven by default only looks at classes named `Test`, not `Tests`. I fixed this in #380.

Thanks @gregturn for verification, the changes look good to me, too. @tommyb82, care to create a pull request with your changes rebased onto current master?

**Comment by tommyb82** [comment]
@olivergierke - thanks, will do so this evening

**Comment by olivergierke** [comment]
:+1:

**Comment by olivergierke** [comment]
PR applied.

**Comment by ydecoux** [comment]
I'm afraid that this fix was only the tip of the iceberg :)
Indeed when following a rel that contains a path variable that needs to be escaped (e.g. http://localhost:8080/springagram/item/{itemId/}) ,then this path variable will be esaped twice.
Once when calling org.springframework.web.util.UriTemplate#expand(java.util.Map<java.lang.String,?>)
And once again when calling org.springframework.web.util.UriComponents#toUri

I've been searching for a fix to this problem but I was not able to find one for the moment ...
