### ISSUE TITLE
Fail gracefully when no request found

### ISSUE THREAD

**Issue by TomRK1089** [spring-projects/spring-hateoas#377]
Right now the HATEOAS methods fail-fast with an `IllegalStateException: Could not find current request via RequestContextHolder. Is this being called from a Spring MVC handler?` when called outside of an actual HTTP request.

However, sometimes I'd like to be able to call `@RestController` methods directly, in the case of integration tests, and in this case there won't be a request. For example, in one of my methods, the controller does:
    
    return ResponseEntity.created(linkTo(EmployeesController.class).slash(persisted.id().get()).toUri()).build();

It'd be nice if there was some property we could set to switch to a 'tolerant' mode for building links, so that `linkTo` either:
* Returns a link with an empty href
* Returns a relative href instead of an absolute href
* Something else?

**Comment by olivergierke** [comment]
We currently just use this in test cases:

```java
private MockHttpServletRequest request;

@Before
public void setUp() {
	request = new MockHttpServletRequest();
	ServletRequestAttributes requestAttributes = new ServletRequestAttributes(request);
	RequestContextHolder.setRequestAttributes(requestAttributes);
}
```

I guess the current design favors the fail fast approach as a missing request basically indicates invalid setup/usage. Leniently falling back to something might mask errors that could've been detected earlier then. Not sure this is a good idea.

**Comment by TomRK1089** [comment]
That seems like a simple enough workaround.

**Comment by rbudzko** [comment]
Hi. While mocking in tests is simply very reasonable,I have recently encountered similar problem while caching (pre caching) resources. When I pre cache very heavy resources I end up with missing request exception. It's reasonable, because for example URL is not known, but do you plan to allow building resources w/o the request? For example by more advanced methods on API, so attributes pulled from request are explicitly passed by the coder?
