### ISSUE TITLE
Impossible to use hateoas in Android using resttemplate

### ISSUE THREAD

**Issue by fritzZz** [spring-projects/spring-hateoas#395]
has anyone tried to use the API developed through springboot and PagingAndSortingRepository interfaces building an Android application?
I need a solution to call my APIs and there is not tool to export easly the client.
In the past I've used swagger to build my client and the solution was good, but using PagingAndSortingRepository there is no way to document the "concrete" apis and not the generics with wildcards.

I've found different peoples that are trying to do that but no good solutions.

**Comment by gregturn** [comment]
Since we don't explicitly test any of this stuff on Android, I'm not sure how we can support it.

If you're looking for a tool to document REST APIs, I'd take a peek at [spring-restdocs](https://github.com/spring-projects/spring-restdocs). Instead of a boiler plate batch of URIs with no concept of links, Spring RestDocs actually lets you write documentation-oriented tests against your code, extract the interacts into bits of asciidoc, which can be plugged into meaningful documentation people can read. Net effect: good reference material + automatically tested/updated bits of hypermedia interaction.

**Comment by gregturn** [comment]
Given we can't reliably keep up with Android platforms, I'm closing this issue.
