### ISSUE TITLE
[DOC] Is PersonResource a different class than Person ?

### ISSUE THREAD

**Issue by kopax** [spring-projects/spring-hateoas#508]
In spring-hateoas, should PersonResource be a different class than Person ?

In the documentation, they have a PersonResource that extends from ResourceSupport, attributes from PersonResource look quite similar to a Person.class.

Also in the PersonResourceAssembler, they use in method `toResource` Person class.

I guess it should be different class. 

How can I maintain the consistency between PersonResource and Person ? 

Should I add a PersonInterface ?

**Comment by gregturn** [comment]
In general I would use Resource<Employee>. Resource<T> extends ResourceSupport, giving you all its benefits while letting you enclose the type details of your Employee domain object. 

You see, ResourceSupport and its many subclasses is meant to to provide a technology neutral way to capture links that can later be tended in json or XML.

In the future please post such questions on stackoverflow.com and tag spring-hateoas instead of opening a big report.

**Comment by kopax** [comment]
> In general I would use Resource<Employee>. Resource<T> extends ResourceSupport, giving you all its benefits while letting you enclose the type details of your Employee domain object.

I don't really understand, how does `ResourceEmployee<Employee> extends ResourceSupport` gives me access to employee attributes ? I rather not to maintain two files.

> You see, ResourceSupport and its many subclasses is meant to to provide a technology neutral way to capture links that can later be tended in json or XML.

I though the resource was the model representation.

> In the future please post such questions on stackoverflow.com and tag spring-hateoas instead of opening a big report.

I will, sorry for that last post.

**Comment by gregturn** [comment]
No, `Resource<Employee>`, using Resource from this project.  It's a container.
