### ISSUE TITLE
ControllerLinkBuilder does not handle multiple X-Forwarded-* headers values

### ISSUE THREAD

**Issue by smilasek** [spring-projects/spring-hateoas#509]
Hi,

Spring Cloud has released Camden.SR2 this week. It includes following bug fix from Spring Cloud Netflix project: https://github.com/spring-cloud/spring-cloud-netflix/issues/959.
particular commit: https://github.com/spring-cloud/spring-cloud-netflix/commit/a38b7b71ac8be9608ac2530dac41cd6298d696cf

Based on that `X-Forwarded-Host`, `X-Forwarded-Port` and `X-Forwarded-Proto` could have multiple values separated by comma.

`X-Forwarded-Host` is already handled properly by `ControllerLinkBuilder` (https://github.com/spring-projects/spring-hateoas/blob/642b6736764068ffeee38379629db5fc15cf927d/src/main/java/org/springframework/hateoas/mvc/ControllerLinkBuilder.java#L236-L256).

`X-Forwarded-Port` and `X-Forwarded-Proto` are not.

Additionally for multiple values of `X-Forwarded-Port` header application is throwing `NumberFormatException`because of input values like `8080,443` etc.

**Comment by otrosien** [comment]
@dsyer could you point to the RFC specifying the X-Forwarded-Port behaviour you implemented in https://github.com/spring-cloud/spring-cloud-netflix/commit/a38b7b71ac8be9608ac2530dac41cd6298d696cf ?

**Comment by otrosien** [comment]
... found it, it's probably https://tools.ietf.org/html/rfc7239#section-4 -- but in this RFC only "by", "for", "host" and "proto" are defined. The spec allows extensions (#section-5.5), but basically, with regards to "port" it means, that it is implementation-specific. On the other hand, UriComponentsBuilder from spring-framework deals with comma-separated ports, since 4.2.0.RELEASE:
https://github.com/spring-projects/spring-framework/blob/1f6f0dc101fb425bd63786ef669b0626a6591543/spring-web/src/main/java/org/springframework/web/util/UriComponentsBuilder.java#L674 / https://github.com/spring-projects/spring-framework/commit/88a14488a194f3795996ba2ac1bf02af639cd7e9#diff-73d13991926d9c9b00031a62c7e39c95

**Comment by dsyer** [comment]
There's no RFC for `X-Forwarded-Port` as far as I know. But it seems to be a common enough convention in proxies that we support it in Spring (https://github.com/spring-projects/spring-framework/blob/1f6f0dc101fb425bd63786ef669b0626a6591543/spring-web/src/main/java/org/springframework/web/util/UriComponentsBuilder.java#L674).

**Comment by otrosien** [comment]
The ControllerLinkBuilder should just delegate this logic to UriComponentsBuilder, which as stated above, is already capable of correctly dealing with the X-Forwarded headers.

**Comment by olivergierke** [comment]
Wouldn't mind to see a PR, @otrosien!

**Comment by olivergierke** [comment]
Thanks to @otrosien, that should be in place now.
