### ISSUE TITLE
Link class should have toURI

### ISSUE THREAD

**Issue by pcornelissen** [spring-projects/spring-hateoas#515]
I am using the Link class a lot to and I have plenty of lines like

        return ResponseEntity.created(new URI(linkBuilder.getLink("{id}").expand(id).getHref())).build();

So I am often converting Links to URIs and as these are required on quite a few APIs in spring, it should be supported out of the box.

If you like it I can create a small PR for it.

**Comment by olivergierke** [comment]
What's supposed to happen if the `Link` is actually templated and not fully expanded yet?

**Comment by pcornelissen** [comment]
the same that happens when you call toHref

**Comment by olivergierke** [comment]
That doesn't work as the resulting String is not a valid URI than and you'd get an exception.

**Comment by pcornelissen** [comment]
but I'd also get an exception when my current code gets the href and tries to create a URI with it

**Comment by olivergierke** [comment]
I don't get the point. The reason we're not exposing API to turn a `Link` into a URI because the code in `Link` can't guarantee that's possible. If we added that API *we* somehow need to decide what to do in that case. Currently it's *you* who has to deal with that situation. I'd argue that's a good situation because *you* know what you want to do in that case, *we* don't. So there's quite a significant change in moving that responsibility around. I don't see how we could give a a decent default answer.

**Comment by pcornelissen** [comment]
Hmm, ok. I see your point. 
Looks like I have to write my own spring-hateoas wrapper library :-)
