### ISSUE TITLE
vnd.error path attribute

### ISSUE THREAD

**Issue by s303** [spring-projects/spring-hateoas#546]
There is a `path` attribute in [vnd.error specification](https://github.com/blongden/vnd.error) but unfortunately there is no such field in `VndErrors` class. It could be very handy to have this filed, to be able to report resource validation errors, for example.

**Comment by gregturn** [comment]
Before adding anything, I'd like a more comprehensive discussion on why we need this one attribute vs. all the others, and what would be a good example of using them in code.

**Comment by douglassparker** [comment]
What do you mean "all the others"? The path attribute is the _only_ attribute that the vnd.error spec proposes that is not already in the VndErrors class. Obviously, it should be supported to comply with the spec. The utility of the attribute is to locate the field in question in the JSON.

**Comment by hughwphamill** [comment]
@gregturn any update on this?

Path would allow a client to know which particular parts of a request caused the error e.g. which fields in the input failed validation.

**Comment by gregturn** [comment]
With my efforts to fix things up through #775, I have submitted https://github.com/blongden/vnd.error/issues/23 (along with PR https://github.com/blongden/vnd.error/pull/24) to improve the spec.

While chewing through this, I have realized that Spring HATEOAS lacks a cohesive error handling strategy. `vnd.error` is confined to HAL, and I feel like we need a little more. So I opened #786.

**Comment by hughwphamill** [comment]
Thanks for the response.  It seems like the draft spec hasn't been touched since 2014.

I wonder if it's something spring should fork and take over?

I'd consider a few more changes for consistency in that spec if it was up to me too. The response structure differs quite depending on the amount/type of errors, I think it would be nicer if it was consistent e.g. returned _embedded.errors even if there was only one error etc, so that you could deserialize it consistently.

I agree that it would be nice to have some proper error infrastructure and a mapper that rendered it in VndError, that said I think VndError for the most part is a good baseline to work off.  In the end you need things like a trace id, message, path and potentially links no matter how it's rendered.

**Comment by gregturn** [comment]
Given how HAL specific `VndErrors` is, we're actually looking at [RFC-7807](https://tools.ietf.org/html/rfc7807).

**Comment by hughwphamill** [comment]
@gregturn Looks like a good spec, and hopefully more maintained.  Thanks for letting me know.

**Comment by hughwphamill** [comment]
@gregturn Is there going to be a standard support for a trace reference (e.g. trace id from Sleuth) or would that have to be built into every custom problem type, do you know?

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/4f3be119c08a0b5db690fe6727632705baae8e4e
