### ISSUE TITLE
`@EnableHypermediaSupport` breaks jackson module registration

### ISSUE THREAD

**Issue by kewne** [spring-projects/spring-hateoas#551]
I've a Spring Boot application where I've added the `jackson-datatype-jsr310` dependency and registered the corresponding module, `JavaTimeModule`.

If I add `@EnableHypermediaSupport` to a configuration class, my serialization tests immediately start failing because `Instant` is serialized as an object instead of a nember.

Attached is a project which reproduces this.
[repro.tar.gz](https://github.com/spring-projects/spring-hateoas/files/848318/repro.tar.gz)

**Comment by gregturn** [comment]
In your scenario, `@JsonTest` disabled hypermedia autoconfiguration.

`HypermediaAutoConfiguration` in Spring Boot will activate Spring HATEOAS while additional autoconfiguring an `ObjectMapper` properly. This would include registering your JavaDateTime Jackson module you registered as a bean. Alas, it's not pulled in with `@JsonTest`.

Your attempt to manually pull things in with `@EnableHypermediaSupport` doesn't cut it either, because you're missing out on the extra wiring done in `HypermediaAutoConfiguration`.

**Comment by gregturn** [comment]
I'm attempting to see how to wire a unit test to pull in `@JsonTest` 's JacksonTester with hypermedia support, but haven't figure out how, yet.

**Comment by gregturn** [comment]
I had a lengthy chat with the Spring Boot team to clarify.

`@JsonTest` is aimed at testing serialization/deserialization. That's why it switches off things like hypermedia.

`@EnableHypermediaSupport` is an annotation Spring Boot switches on automatically with autoconfig. The fact that you manually put it into your code actually disabled Boot's HypermediaAutoConfiguration support.

* First, don't use `@EnableHypermediaSupport`
* Second, if you wish to test any of the JSON features in their HAL-based form, you would be better off using `@MockMvcTest` and making mock calls to the related controller. This grants you `jsonPath()` predicates to inspect stuff.
* If you JUST want to verify things like your module getting registered, you can use `@JsonTest`, but the JSON links won't appear as they do in production.

Personally, I would shift from `@JsonTest` to `@MockMvcTest` so you don't accidentally code a test case against the wrong form of JSON.

**Comment by philwebb** [comment]
There's a bug in Spring Boot that's stopping `@AutoConfigureJsonTesters` from always working. See https://github.com/spring-projects/spring-boot/issues/9515 for a workaround until it's fixed.

**Comment by gregturn** [comment]
I'm closing this issue since the problem appears resolves by https://github.com/spring-projects/spring-boot/issues/9515.

You can either put this on your code:

```
@RunWith(SpringRunner.class)
@SpringBootTest
@AutoConfigureJsonTesters
public class DemoApplicationTests {
...
```
...and have access to a `JacksonTester<Entity>` object, which works with your Java8 time module AND will create a HAL Object Mapper.

Or you can merely use...

```
@RunWith(SpringRunner.class)
@JsonTest
public class DemoApplicationTests {
...
```
...and ALSO have the same `JacksonTester` object. However in this situation, hypermedia is not enabled so I would NOT test any of the links since HAL (nor any other mediatype) will be rendered.

Either way, the ability to inject a `JacksonTester` is fixed.
