### ISSUE TITLE
Interaction with org.springframework.plugin:spring-plugin-core

### ISSUE THREAD

**Issue by elgohr** [spring-projects/spring-hateoas#613]
I'm using org.springframework.boot/spring-boot-starter-hateoas for integration in Spring Boot.
A few days ago I also added Swagger. In this way it turned out that my responses, which had been in the format 
```json
content:
_links:
```
are restructured to
```json
_embedded:
   content:
   _links:
```
Then I digged a little deeper into transitive dependencies of Swagger. It turned out that org.springframework.plugin:spring-plugin-core is responsible for this behaviour.
Simple question: Why? :-D

**Comment by olivergierke** [comment]
I don't think we can answer questions about Swagger here. Spring Plugin is a general plugin mechanism that's used inside Spring HATEOAS to pick up user defined extensions of SPIs (`RelProvider` etc.).

Actually, what you describe is expected behavior. Spring Boot's auto-configuration enables Spring HATEOAS' support for HAL out of the box, which is what you see.

Generally speaking, please use StackOverflow for general questions.
