### ISSUE TITLE
Rel name based on resource instance instead of resource class

### ISSUE THREAD

**Issue by joostfarla** [spring-projects/spring-hateoas#614]
Our application uses a single Resource class to serve multiple types of data. This is because the different data types are dynamically determined based on external configuration. Simplified code:

```java
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import java.util.Map;
import org.springframework.hateoas.ResourceSupport;

public class Resource extends ResourceSupport {

  private Map<String, Object> propertyMap;

  public Resource(Map<String, Object> propertyMap) {
    super();
    this.propertyMap = propertyMap;
  }

  @JsonAnyGetter
  public Map<String, Object> getPropertyMap() {
    return propertyMap;
  }
}
```

They get instantiated like this:
```java
Resource car = new Resource(ImmutableMap.of("brand", "Porsche"));
Resource building = new Resource(ImmutableMap.of("height", 84));
```

When embedding those resources, e.g. for a collection, the current RelProvider API only allows us to derive the rel name from the class of the resource (which is always `Resource`). In our case, the rel name cannot be derived from the class, but can differ per  instance of the class (e.g. `cars `or `buildings`). Is this possible?

**Comment by gregturn** [comment]
The trick is that things like HAL formatting is built up on the premise that your types are laid out as classes. You have kind of subverted this by using maps everywhere, hiding the typing inside the data itself. Hence, Spring HATEOAS can't tell one object from another, since everything is the same type, a map. Kind of smells like JavaScript where their "classes" really are just property maps.

Trying to put a different lookup based on the object itself, and NOT using its type, would require a major rewrite of the framework that I'm not sure if of great value. The system is built on strong typing whereas your solution appears to be baked on a very weak, string-based typing.

**Comment by joostfarla** [comment]
Thanks for the clarification! Our case is probably a little bit too specific and requires a more manual approach.
