### ISSUE TITLE
ResourceSupport.getId() too restrictive

### ISSUE THREAD

**Issue by deepakpol** [spring-projects/spring-hateoas#66]
Having ResourceSupport.getId() method return Link is too restrictive IMO. It makes my representation unable to have id field and corresponding getId() method with different type. It seems a very common use case to assume in UI that the id field of resource would return actual id of the resource and not a link.
Probably ResourceSupport could also be made generic where the id return type is passed by  the class extending ResourceSupport.

**Comment by ravindranathakila** [comment]
If it helps, http://jsonapi.org/format/#document-structure-resource-objects contains an "id" field which in the example is a number. 

I think having a "Link" for id makes sense too since it points to a resource which is identified by this given id.

But in a traditional perspective of id's this is too restrictive.

**Comment by cy33hc** [comment]
@olivergierke The reason put forward about leaking internal id is completely unsound. If anybody know rest then they will know from the URI, the internal Id anyway since you have just included it in the Link.

**Comment by miguelcobain** [comment]
@cy33hc a hateoas client can't infer anything from an URL.
The reason is because the URL is something given to it by the server, for the client to follow.
The server can change the url at anytime, and the system shouldn't behave any differently.

Also, no one is suggesting to have ids in urls either. You don't have to.

Extracting an id from an url would mean some "out of bounds information" has happened, which is something incompatible with hateoas.
The self href should be unique and should suffice for those needs.

**Comment by stephaneeybert** [comment]
@olivergierke  I agree that HATEOAS is a nice idea, that having all URIs considered internals, shaped, issued and controlled by the server is sensible, as it prevents coupling between the client and the server. But even the best way to do something is not the only way to do it. And many of us will go for a middle way. If the framework would allow that, it would not occupy this prime real estate called id. I still stand by my first comment I made 2 years ago. Today the framework names this data for what it means, an id, and not for what it is, a URI. It is too bad that the designers ask our clients front ends to be agnostic about it, when they themselves are not.

**Comment by ranajit-jana** [comment]
Issue still showing up as get Link is returning something like below


<http://hostname:port/entity/id>;rel="self"


I cannot use it directly as link but need to do processing.

I will be happy if i get as below
**http://hostname:port/entity/id**

and not get other characters like <> or ;rel=self

**Comment by kopax** [comment]
I am sad to have such a good framework in my hand and cannot use it has it is!

**Comment by gazeciarz** [comment]
I come with the same problem. Is there any update on this topic?

**Comment by kopax** [comment]
Can we have an update on this topic ? This has been like this for a while, it's a shame we cannot use such strong tool.

**Comment by aardelean** [comment]
same problem here. Not all projects can be that smoothly be upgraded to use spring hateos if it means heavy refactoring on multiple systems at once.
Rest was known for its flexibility and json for no-schema. Now we are enforcing strict standards and give schema as arguments to why. Might as well go back to SOAP altogether. Pretty annoyed at the moment that I will have to do my own resource deserialisation just because of one word in ResourceSupport.

**Comment by kopax** [comment]
Maybe there is a way to fork and build our own version with less strict standard

**Comment by miguelcobain** [comment]
> Rest was known for its flexibility and json for no-schema.

I think you mean HTTP APIs were known for it's flexibility.
REST *always* had these kind of constraints.

I think my 2 year comment still holds up pretty well: https://github.com/spring-projects/spring-hateoas/issues/66#issuecomment-34968272

**Comment by sshcherbakov** [comment]
Running into a concrete example where I need "id" field in the response body that _doesn't have anything to do with the resource or underlying database entity id_ and it still gets suppressed by Spring.

I'm storing the Tinkerpop JSON in the MongoDB:
http://tinkerpop.apache.org/docs/current/reference/#graphson-reader-writer
Both Tinkerpop 2.x and 3.x recognizes and can parse the JSON with "_id" (2.x) and "id" (3.x) in the JSON. 
Those IDs have nothing to do with the entity or resource that stores that JSON! and those are the properties of deep embedded objects in the JSON that my service returns.

My problem is that I cannot use 
````
@Override
    public void configureRepositoryRestConfiguration(RepositoryRestConfiguration config) {
        super.configureRepositoryRestConfiguration(config);
        config.exposeIdsFor(
                MyEmbeddedType.class,
````

because that seems to work for high level persistency entities only and I have a deep embedded object (again, "id" is prescribed by some other tool format and the property is not of the main or any of mine application entities).

**Comment by elnur** [comment]
> In REST the id of a resource is its URI (hence Unique Resource Identifier).

The problems start here. This logic is flawed.

The URI I used to fetch a resource might be called its ID — I don't argue with that. What does this have to do with the ID field of the backing entity or its resource representation though? It's my right to assign whatever meaning I want to the field named `id`.

The ID might be some number displayed to a user in the UI. Say an order at some online store has an ID associated with it. If I have a problem with my order, I call their support and tell them the order ID. Not all IDs are meant to be hidden from end users. They can change the order URI format as much as they want, but an order's ID will stay the same.

And people will and do this anyway. They just have to work around the library with ugly and unnecessary hacks.

**Comment by miguelcobain** [comment]
@elnur for the record, your argument is sound and convinced me.

**Comment by olivergierke** [comment]
> The problems start here. This logic is flawed.

First, then you better complain to Roy. It's not that I made up the rules here. Second, there's no logic in this statement, as it's a plain statement. So the logic, that the logic is flawed, is flawed.

> The URI I used to fetch a resource might be called its ID — I don't argue with that. What does this have to do with the ID field of the backing entity or its resource representation though? It's my right to assign whatever meaning I want to the field named id.

Nothing. I didn't think, that I have to get even more fundamental than in my original comment, but apparently I have to :). There's a class that exposes the identifier of a resource. The identifier of a resource is its URI. Hence the class exposes that URI for the accessor of the ID. That's simple, straight forward, easy. If you opt into extending that class you express that you're willing to adhere to follow the rules and concepts. Extending it and then complaining about the rules is… weird.

> The ID might be some number displayed to a user in the UI.

REST doesn't know about a UI.

> Say an order at some online store has an ID associated with it.

REST doesn't know about an online store.

> If I have a problem with my order, I call their support and tell them the order ID. Not all IDs are meant to be hidden from end users.

Right, as they're just part of the representation of the resource. From a resource point of view, it is *not* its identifier. That's all the type is implementing. You basically mix up your domain's bounded context with the bounded context of REST itself, where domain terms like resource, identifier etc. have well defined semantics. I can't simply forward you domains understanding of an ID into the REST context as — unless you're using URIs in your domain — they don't fit the rules that that context implies.

> The store can change the order URI format as much as they want, but an order's ID will stay the same.

So what? You're basically trying to force a different, application specific kind of identity onto something that's got nothing to do with your application. That's a fundamentally flawed approach. Not because I say so, but because you basically start violating the architectural constraints that are in place to give you certain effects of your architecture. It's not up to me for you to decide what to do, and nobody forces you to follow the constraints, but just don't expect a library that wants to help people to conform to the constraints to actually get to the effects following those constraints to weaken the rules, just because you feel they're limiting. They in fact are, for a reason.

**Comment by stephaneeybert** [comment]
I stand by Oliver's view but holding that view does not mean we have to name the resource identifier with the "id" word. I haven't yet seen a counter argument on my comment of Nov 14 2013. The issue here, as I see it, is naming it "id" when it could have been named "link".

**Comment by olivergierke** [comment]
Hm, I think that's problematic as it's just using the term for a different, much broader concept in REST to describe a domain concept that has very well-defined semantics.

**Comment by stephaneeybert** [comment]
It could also have been named resourceId, restUrl, etc.. named after what it is, rather than after what it means.

**Comment by gregturn** [comment]
I don't get the point about swapping "id" with "link". What if that shadows someone else's domain object? Change again? And why? 

Now we're fiddling around with asking the framework to accommodate WHAT to call the resource's URI identifier to appease everyone. When we could have just done "id" and moved on to building hypermedia resources. 

Besides, if we use `Resource<Foo>`, doesn't that solve most of this issue anyway? With that, the domain object and the resource object are nicely separated by a container with a contract (I've always favored that over `Foo extends ResourceSupport`)

**Comment by elnur** [comment]
> First, then you better complain to Roy (for reference). It's not that I made up the rules here.

Please cite where it says I can't have an `id` field in resource representations.

> If you opt into extending that class you express that you're willing to adhere to follow the rules and concepts. Extending it and then complaining about the rules is… weird.

Basically, I extend `ResourceSupport` to inherit links manipulating methods and to create a resource assembler for it. I can't use the library's `ResourceAssembler` without extending `ResourceSupport`.

Now, for me, a resource is a DTO I use to decouple domain types from their representations. I can add whatever fields I want to the resource type and they will get exposed in the representation. The fields I don't add don't get exposed.

Since most of my domain types have an ID field — artificial or natural — I want to expose them in representations as well. But I can't do that when extending `ResourceSupport` *without resorting to workarounds*. Having to resort to workarounds is the whole point of this issue in the first place.

A suggested solution for that problem is extending `Resource<T>` instead. If I pass my domain object to the `content` field of `Resource<T>`, all fields of the domain object will get exposed if autodetection is enabled. To solve that problem, I have to add Jackson annotations to my domain type or create a Jackson mixin to either hide unnecessary fields if autodetection is enabled, or to expose necessary fields if autodetection is disabled. Or I have to create another DTO layer between my domain types and resources. And that becomes pretty meta.

And all I wanted was to *easily* add links to my resources. Without having to deal with all that ID field related pain.

And I bet that for most users of Spring HATEOAS adding links to resources is the first and main reason to use the library. Sure, it has nice additional features on top of that, but if I can't extend `ResourceSupport` and `ResourceAssembler` which are the backbone of the library, I might as well just not use it at all.

Maybe a solution to the problem would be adding a class above `ResourseSupport` that just adds support for links without messing with the ID field of resources?

**Comment by mcnichol** [comment]
> > First, then you better complain to Roy (for reference). It's not that I made up the rules here.

> Please cite where it says I can't have an id field in resource representations.

@elnur 

There's a hyperbole used in the [Introduction](https://www.ics.uci.edu/~fielding/pubs/dissertation/introduction.htm) of his dissertation based on a Monty Python skit *The Architects Sketch*

In this sketch, the architect presents the design of a block of apartment flats built with the functionality of a slaughterhouse.  The claims are made that this is the best slaughterhouse ever built but obviously terrible for actual tenants.  It goes on with another presentation but the point is made.

Immediately after this, Roy makes the statement:

> At least some of this behavior within the software industry is due to a lack of understanding of why a given set of architectural constraints is useful. 
> 
> In other words, the reasoning behind good software architectures is not apparent to designers when those architectures are selected for reuse.

It's guiding your architectural style ( `ResourceSupport.getId()` returning the URI ) vs a coding style you would like that would alter the architecture.  

The id of the ResourceSupport would no longer be the URI but your domain objects.

It sounds like it is doing its intended job and you are not aligned||understanding the architecture rules behind it.

**Comment by Panthro** [comment]
I surely understand the architectural designs behind the decision that was made, I can relate to them and I don't question them.

The 1kk question is:

**Why the default behaviour cannot be extended/modified?**

If we are open to a more extensible approach, I'd happily create  PR where this behaviour is by default enable but with a property it can be changed.

**Comment by gregturn** [comment]
There is already an escape hatch: `Resource<T>`. 

I don't see how to make these types any more extensible and not also cause considerable issues in the mediatype serializers and deserializers.

**Comment by Delmonte3161** [comment]
I am also having this issue and following other's suggestion I have re-named the entity class field (cannot rename the DB column).  The field in the DB is "id".  The field in my entity class is called "personId", is annotated as @Id and is mapped to "id" via the @Column attribute.  The Resource/ResourceSupport is STILL not showing me this id when rendering the json.  Why in the world can I not see "personId" in the json?  Every other field from the entity is shown fine.

**Comment by gregturn** [comment]
Can you show the results of JSON when you use `Resource<Person>`?

**Comment by Panthro** [comment]
I disabled the whole think all together and stopped using spring hateoas just because of this issue.

In my opinion is ridiculous that the framework **decides** how it should be used, I work for clients that I cannot argue saying "oh, but it's better if you don't expose your ID's", its their product and that is how they want, I just have to implement it.

Now the fact that I had to remove it entirely because of this issue is ridiculous.

**Comment by ceefour** [comment]
"Simple things should be simple, complex things should be possible." - Alan Kay

In this case, a simple thing is made impossible.

Spring Data REST does make it [possible to expose IDs with some configuration](https://stackoverflow.com/questions/30912826/expose-all-ids-when-using-spring-data-rest).

I (and many others) would argue there are various cases in which exposed ID is beneficial or even required. Interoperability with other systems is one. Had GeoNames API used Spring HATEOAS, we'll never be able to use GeoNames IDs, instead we always use GeoNames URIs. Using GeoNames IDs makes a lot of things possible and efficient.

GraphQL is another world where we're not restricted to resources-as-URI view. Most GraphQL endpoints use IDs, I have yet to find one that uses URIs as the "primary key" although it's definitely possible with GraphQL.

**Comment by olivergierke** [comment]
I guess we can close the discussion as the arguments have stayed the same for quite some time and I don't like repeating myself. However, there's a certain irony in bringing up GraphQL as your defense in a library that cares about REST ;).
