### ISSUE TITLE
Main Spring HATEOAS site points to old release 0.23 to be current (instead of 0.24)

### ISSUE THREAD

**Issue by ahus1** [spring-projects/spring-hateoas#683]
The website 
http://projects.spring.io/spring-hateoas/
names 0.23 to be the current release. But as of October 2017, 0.24 is the current version. 

Also the badge on the Github repository https://github.com/spring-projects/spring-hateoas lists 0.23 to be the current release. 

Both symptoms might have the same cause. 

As 0.24 add some nice features about customizing links it would be helpful for people get to the latest version.

![spring-hateoas-version](https://user-images.githubusercontent.com/3957921/34156642-612556e6-e4be-11e7-9d8f-8c03d442215f.png)

![spring-hateoas-version-2](https://user-images.githubusercontent.com/3957921/34156672-7f111e42-e4be-11e7-9cf7-853fe3d015c1.png)

**Comment by gregturn** [comment]
Resolved.

**Comment by gregturn** [comment]
I've closed this issue because http://projects.spring.io/spring-hateoas/ has been properly updated. For some reason (caching?) the badges on the github site display 0.23.0, however https://spring.io/badges/spring-hateoas/ga.svg will show 0.24.0 (correctly).

Might require a certain timeout to occur.
