### ISSUE TITLE
No way to configure PagedResourcesAssembler to generate one-indexed pagination links.

### ISSUE THREAD

**Issue by ahmedjaad** [spring-projects/spring-hateoas#727]
By default all pagination links added by `PagedResourcesAssembler` are zero-indexed, one would expect a way to configure these links to be one-indexed, there seems to be none. My workaround is to have an extended class of `PageImpl ` and tweak methods like `previousPageable`, `nextPageable`, `hasPrevious` `hasNext` and so on that are being used internally by `PagedResourcesAssembler` to generate these links. and pass in this `CustomPage` instance to `toResource` method of  `PagedResourcesAssembler` .This approach does not look 'clean' to me. Because this Custom Page might accidentally be used somewhere else in the code base and produce undesirable results. This approach at least partially solves the problem, partially because 'first' link will always have "page=0". Could there be a shorter and cleaner way to configure `PagedResourcesAssembler` to add one-ndexed list of pagination links?

**Comment by gregturn** [comment]
A) This issue is specifically about Spring Data REST, considering `PagedResourcesAssembler` is a part of Spring Data Commons, for which Spring HATEOAS has no knowledge of. In fact, all Spring HATEOAS has is a value class `PageMetadata` contained inside `PagedResources`. Spring HATEOAS doesn't make any decisions about HOW to use this construct. The only thing found are unit tests that can presume anything.

B) Why is the indexing of pages so critical? In REST, actual URIs aren't critical. Only rels (relationships) should be pertinent. In fact, this is highlighted by the fact that Spring HATEOAS doesn't care what values are put into `PageMetadata`. 

C) This concept of paging is actually codified in Spring Data Commons, since it's an undercurrent among all the data stores, and is not confined to Spring Data REST. Hence, you'd have to peek in there to see that Spring Data Commons has instituted a 0-based paging system, so to insert an alternative would be a little more complicated than just tweaking the output of a Spring Data REST HAL document.

**Comment by ahmedjaad** [comment]
That is right about page indexing not being critical, reason that drove me to have this work around is because with `HateoasPageableHandlerMethodArgumentResolver.setOneIndexedParameters(true);` configuration in place, it caused all sort of problems, consider this example
GET /products?page=1&size=1
```
{
"_embedded":{
"products":[
{
"name": "product1",
"_links":{"self":{"href": "http://localhost:8080/products/product1" }}
}
]
},
"_links":{
"first":{
"href": "http://localhost:8080/products?page=0&size=1"
},
"self":{
"href": "http://localhost:8080/products?page=0&size=1"
},
"next":{
"href": "http://localhost:8080/products?page=1&size=1"
},
"last":{
"href": "http://localhost:8080/products?page=2&size=1"
}
},
"page":{
"size": 1,
"totalElements": 3,
"totalPages": 3,
"number": 0
}
}
```
See the point here, 'next' and 'last' links are wrong, next should be `http://localhost:8080/products?page=2&size=1` and since totalElements = 3  'last' link should be `http://localhost:8080/products?page=2&size=1`.
Maybe I should have have created this as an issue instead.
I'm not very knowledgeable on spring projects and their components, where would be the right place to create this issue.

**Comment by gregturn** [comment]
I’d start here by opening a ticket here => https://github.com/spring-projects/spring-data-commons

**Comment by gregturn** [comment]
Closed in favor of https://jira.spring.io/browse/DATACMNS-1668.
