### ISSUE TITLE
Removal of spring-plugin library

### ISSUE THREAD

**Issue by markpollack** [spring-projects/spring-hateoas#863]
Is the dependency on this project still required or do features in the current version spring make this superfluous.  Also, ATM spring-plugin pulls in quite the old version of the spring - which is how it got noticed on Data Flow since the client library pulls in spring-hateoas.

**Comment by odrotbohm** [comment]
Yes the library is still required. The master branch already updated to 2.0 M1 of it. Both Spring Plugin in 2.0 as well as HATEOAS 1.0 upgrade to the latest Spring 5.1 dependencies.

There's compatibility constraints in to which Spring version we can upgrade in the 0.x (HATEOAS) or 1.x (Spring Plugin) versions respectively. We'd need to issue minor version releases to at least upgrade to the latest 4.1 releases. We'd much rather concentrate on the upcoming major versions.

Doesn't Data Flow's client library use the Spring BOM so that versions are aligned to more recent versions of it? We have build profiles that ensure the compatibility with the latest versions of Spring, i.e. it should be no problem to use the legacy versions of the libraries on current Spring. In fact, Boot runs them on those.
